[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"


[context.production.environment]
  HUGO_VERSION = "0.41"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo version"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.41"